"""AI image and URL analysis engine for DailyStream.

This module provides AI-powered analysis of screenshots and URLs using the
Anthropic Claude API.  It is designed with a **data-separation architecture**:
AI analysis results are stored in a separate ``ai_analyses.json`` file per
pipeline, linked to the original ``context.json`` entries via
``entry_index + timestamp`` indexing.

Two analysis modes are supported:

- **realtime**: each entry is analysed independently right after it is
  captured.  A background serial queue (``AnalysisQueue``) ensures
  ``ai_analyses.json`` writes are never concurrent.
- **daily_report**: analysis happens in batch at workspace-end time.
  An additional cross-pipeline summary is generated by AI.

The ``anthropic`` SDK is an *optional* dependency.  When it is not
installed every public function degrades gracefully (returns ``None`` /
does nothing) and emits a single warning.
"""

from __future__ import annotations

import base64
import json
import logging
import os
import queue
import threading
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import TYPE_CHECKING, Optional

from .config import read_json, write_json, now_iso

if TYPE_CHECKING:
    from .config import Config

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Optional dependency: anthropic
# ---------------------------------------------------------------------------

_anthropic = None  # type: ignore[assignment]
_ANTHROPIC_AVAILABLE = False

try:
    import anthropic as _anthropic  # type: ignore[no-redef]

    _ANTHROPIC_AVAILABLE = True
except ImportError:
    pass

# Try optional Pillow for image compression
_PIL_AVAILABLE = False
try:
    from PIL import Image  # noqa: F401

    _PIL_AVAILABLE = True
except ImportError:
    pass


def _warn_no_anthropic() -> None:
    logger.warning(
        "anthropic SDK is not installed — AI analysis is disabled. "
        "Install with: pip install 'dailystream[ai]'"
    )


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class AnalysisResult:
    """A single AI analysis result.

    Linked to the corresponding ``context.json`` entry via
    ``entry_index`` (array position) and ``timestamp`` (double-check).
    """

    entry_index: int
    timestamp: str  # must match the entry's timestamp
    input_type: str  # "image" | "url"
    description: str  # AI-generated description
    category: str  # coding / design / browsing / document / communication / other
    key_elements: list[str] = field(default_factory=list)
    analyzed_at: str = ""
    status: str = "completed"  # "completed" | "failed"
    error: str = ""

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "AnalysisResult":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

    @classmethod
    def failed(
        cls,
        entry_index: int,
        timestamp: str,
        input_type: str,
        error: str,
    ) -> "AnalysisResult":
        """Create a failed result placeholder."""
        return cls(
            entry_index=entry_index,
            timestamp=timestamp,
            input_type=input_type,
            description="",
            category="",
            key_elements=[],
            analyzed_at=now_iso(),
            status="failed",
            error=error,
        )


# ---------------------------------------------------------------------------
# AnalysisStore — manages per-pipeline ai_analyses.json
# ---------------------------------------------------------------------------


class AnalysisStore:
    """Read / write the ``ai_analyses.json`` file for one pipeline.

    File schema::

        {
          "pipeline_name": "...",
          "model": "...",
          "analyses": [ {AnalysisResult dict}, ... ],
          "daily_summary": null | "..."
        }
    """

    def __init__(self, analyses_path: Path, pipeline_name: str = "") -> None:
        self._path = analyses_path
        self._pipeline_name = pipeline_name

    # -- core I/O ---------------------------------------------------------

    def load(self) -> dict:
        """Load the analyses file (or return a fresh skeleton)."""
        if self._path.exists():
            return read_json(self._path)
        return {
            "pipeline_name": self._pipeline_name,
            "model": "",
            "analyses": [],
            "daily_summary": None,
        }

    def _save(self, data: dict) -> None:
        write_json(self._path, data)

    # -- mutations --------------------------------------------------------

    def append(self, result: AnalysisResult) -> None:
        """Append an analysis result (thread-safe when used via queue)."""
        data = self.load()
        data["analyses"].append(result.to_dict())
        self._save(data)

    def set_model(self, model: str) -> None:
        data = self.load()
        data["model"] = model
        self._save(data)

    def set_daily_summary(self, summary: str) -> None:
        data = self.load()
        data["daily_summary"] = summary
        self._save(data)

    # -- queries ----------------------------------------------------------

    def get_by_entry_index(self, index: int) -> Optional[dict]:
        data = self.load()
        for a in data.get("analyses", []):
            if a.get("entry_index") == index:
                return a
        return None

    def has_analysis(self, entry_index: int, timestamp: str) -> bool:
        """Check if an entry already has an analysis (by index + timestamp)."""
        a = self.get_by_entry_index(entry_index)
        if a is None:
            return False
        return a.get("timestamp") == timestamp

    def get_all_completed(self) -> list[dict]:
        data = self.load()
        return [
            a for a in data.get("analyses", []) if a.get("status") == "completed"
        ]

    def get_all(self) -> list[dict]:
        data = self.load()
        return data.get("analyses", [])


# ---------------------------------------------------------------------------
# API key resolution
# ---------------------------------------------------------------------------


def get_ai_api_key(config: "Config") -> str:
    """Return the AI API key.

    Priority: ``DAILYSTREAM_AI_KEY`` env var → ``config.ai_api_key``.
    """
    return os.environ.get("DAILYSTREAM_AI_KEY", "") or getattr(
        config, "ai_api_key", ""
    )


# ---------------------------------------------------------------------------
# Image compression helper
# ---------------------------------------------------------------------------


def _compress_image(image_path: Path, max_size_kb: int = 150) -> bytes:
    """Compress an image to JPEG bytes, capped at *max_size_kb*.

    Falls back to reading the raw file when Pillow is unavailable.
    """
    if _PIL_AVAILABLE:
        from PIL import Image as PILImage

        img = PILImage.open(image_path)
        # Downscale to max 1280px width (preserves aspect ratio)
        max_width = 1280
        if img.width > max_width:
            ratio = max_width / img.width
            img = img.resize(
                (max_width, int(img.height * ratio)),
                PILImage.Resampling.LANCZOS,
            )
        # Convert RGBA → RGB for JPEG
        if img.mode in ("RGBA", "P"):
            img = img.convert("RGB")

        import io

        quality = 85
        while quality >= 20:
            buf = io.BytesIO()
            img.save(buf, format="JPEG", quality=quality, optimize=True)
            if buf.tell() / 1024 <= max_size_kb:
                return buf.getvalue()
            quality -= 10

        # Worst case
        buf = io.BytesIO()
        img.save(buf, format="JPEG", quality=20, optimize=True)
        return buf.getvalue()

    # No Pillow — read raw bytes
    return image_path.read_bytes()


def _encode_image_base64(image_path: Path, max_size_kb: int = 150) -> str:
    """Return a base64-encoded string of the (optionally compressed) image."""
    raw = _compress_image(image_path, max_size_kb)
    return base64.b64encode(raw).decode("ascii")


def _detect_media_type(image_path: Path) -> str:
    suffix = image_path.suffix.lower()
    mapping = {
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".gif": "image/gif",
        ".webp": "image/webp",
    }
    return mapping.get(suffix, "image/png")


# ---------------------------------------------------------------------------
# Default prompts
# ---------------------------------------------------------------------------

_DEFAULT_IMAGE_PROMPT = """\
Analyze this screenshot. Respond in JSON only (no markdown fences):
{
  "description": "A concise description of what is shown (1-2 sentences)",
  "category": "one of: coding, design, browsing, document, communication, other",
  "key_elements": ["element1", "element2", "..."]
}
"""

_DEFAULT_URL_PROMPT = """\
Summarize the content of the following URL in JSON only (no markdown fences):
URL: {url}
{
  "description": "A concise summary of the page content (1-2 sentences)",
  "category": "one of: coding, design, browsing, document, communication, other",
  "key_elements": ["element1", "element2", "..."]
}
"""

_DEFAULT_DAILY_SUMMARY_PROMPT = """\
You are summarizing a work day based on the analysis of screenshots and URLs
captured during various work tasks (pipelines).

For each pipeline below, I provide the pipeline name, its description/goal,
and a list of AI-analysed entries.  Please generate:
1. A short summary for each pipeline (1-2 sentences).
2. An overall daily summary (2-4 sentences) that highlights the main
   activities, achievements, and context switches.

Respond in JSON only (no markdown fences):
{{
  "pipeline_summaries": {{
    "<pipeline_name>": "<summary>",
    ...
  }},
  "overall_summary": "<daily summary>"
}}

--- Pipeline data ---
{pipeline_data}
"""


# ---------------------------------------------------------------------------
# ImageAnalyzer — core AI calling logic
# ---------------------------------------------------------------------------


class ImageAnalyzer:
    """AI analysis engine wrapping the Anthropic Claude API.

    When ``anthropic`` is not installed every method silently returns
    ``None``.
    """

    def __init__(self, config: "Config") -> None:
        self._config = config
        self._client = None
        self._model = getattr(config, "ai_model", "claude-sonnet-4-20250514")
        self._timeout = getattr(config, "ai_timeout", 30)
        self._max_tokens = 1024
        self._max_image_size_kb = getattr(config, "ai_max_image_size_kb", 150)
        self._custom_prompt = getattr(config, "ai_prompt", "")
        self._init_client()

    def _init_client(self) -> None:
        if not _ANTHROPIC_AVAILABLE:
            _warn_no_anthropic()
            return
        api_key = get_ai_api_key(self._config)
        if not api_key:
            logger.warning("No AI API key configured — AI analysis disabled.")
            return
        self._client = _anthropic.Anthropic(api_key=api_key, timeout=self._timeout)

    @property
    def available(self) -> bool:
        return self._client is not None

    # -- single-image analysis --------------------------------------------

    def analyze_image(
        self,
        image_path: Path,
        user_hint: str = "",
        context: str = "",
    ) -> Optional[AnalysisResult]:
        """Analyse a single screenshot.

        Parameters
        ----------
        user_hint
            The user's description from the capture dialog (e.g.
            "help me check this error").  Used as an extra prompt hint.
        context
            Pipeline-level context (daily_report mode only).
        """
        if not self.available:
            return None

        img_b64 = _encode_image_base64(image_path, self._max_image_size_kb)
        media_type = _detect_media_type(image_path)

        # Build the text part of the message
        prompt_parts: list[str] = []
        if self._custom_prompt:
            prompt_parts.append(self._custom_prompt)
        else:
            prompt_parts.append(_DEFAULT_IMAGE_PROMPT)
        if user_hint:
            prompt_parts.append(f"\nUser note: {user_hint}")
        if context:
            prompt_parts.append(f"\nContext: {context}")

        text_content = "\n".join(prompt_parts)

        try:
            response = self._client.messages.create(
                model=self._model,
                max_tokens=self._max_tokens,
                messages=[
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "image",
                                "source": {
                                    "type": "base64",
                                    "media_type": media_type,
                                    "data": img_b64,
                                },
                            },
                            {
                                "type": "text",
                                "text": text_content,
                            },
                        ],
                    }
                ],
            )
            return self._parse_response(response, input_type="image")
        except Exception as e:
            logger.error(f"AI image analysis failed: {e}")
            return None

    # -- URL analysis -----------------------------------------------------

    def analyze_url(
        self,
        url: str,
        user_hint: str = "",
        context: str = "",
    ) -> Optional[AnalysisResult]:
        """Analyse a URL (text-only request)."""
        if not self.available:
            return None

        prompt_parts: list[str] = []
        if self._custom_prompt:
            prompt_parts.append(self._custom_prompt.replace("{url}", url))
        else:
            prompt_parts.append(_DEFAULT_URL_PROMPT.replace("{url}", url))
        if user_hint:
            prompt_parts.append(f"\nUser note: {user_hint}")
        if context:
            prompt_parts.append(f"\nContext: {context}")

        text_content = "\n".join(prompt_parts)

        try:
            response = self._client.messages.create(
                model=self._model,
                max_tokens=self._max_tokens,
                messages=[
                    {
                        "role": "user",
                        "content": text_content,
                    }
                ],
            )
            return self._parse_response(response, input_type="url")
        except Exception as e:
            logger.error(f"AI URL analysis failed: {e}")
            return None

    # -- batch analysis (daily_report) ------------------------------------

    def batch_analyze_entries(
        self,
        entries: list[dict],
        pipeline_name: str = "",
        pipeline_context: str = "",
    ) -> list[Optional[AnalysisResult]]:
        """Analyse a list of entries one by one.

        For ``daily_report`` mode the *pipeline_context* string is
        included so the AI can see the bigger picture.

        Returns a list of results (``None`` for entries that cannot
        be analysed or that failed).
        """
        results: list[Optional[AnalysisResult]] = []
        for entry in entries:
            itype = entry.get("input_type", "")
            content = entry.get("input_content", "")
            user_hint = entry.get("description", "")

            result: Optional[AnalysisResult] = None
            if itype == "image" and Path(content).exists():
                result = self.analyze_image(
                    Path(content),
                    user_hint=user_hint,
                    context=pipeline_context,
                )
            elif itype == "url":
                result = self.analyze_url(
                    content,
                    user_hint=user_hint,
                    context=pipeline_context,
                )

            results.append(result)

            # Small delay between requests to be polite to the API
            if result is not None:
                time.sleep(0.3)

        return results

    # -- daily summary (cross-pipeline) -----------------------------------

    def generate_daily_summary_text(
        self,
        pipeline_data_text: str,
    ) -> Optional[dict]:
        """Call AI to produce a cross-pipeline daily work summary.

        *pipeline_data_text* is a pre-formatted string with each
        pipeline's name, description, and entry analysis descriptions.
        Only text — no images — is sent, so token cost is very low.
        """
        if not self.available:
            return None

        prompt = _DEFAULT_DAILY_SUMMARY_PROMPT.replace(
            "{pipeline_data}", pipeline_data_text
        )

        try:
            response = self._client.messages.create(
                model=self._model,
                max_tokens=2048,
                messages=[{"role": "user", "content": prompt}],
            )
            raw = self._extract_text(response)
            return self._parse_json_safe(raw)
        except Exception as e:
            logger.error(f"AI daily summary failed: {e}")
            return None

    # -- response parsing helpers -----------------------------------------

    def _parse_response(
        self, response, *, input_type: str
    ) -> Optional[AnalysisResult]:
        raw = self._extract_text(response)
        parsed = self._parse_json_safe(raw)
        if parsed is None:
            # Fall back to using raw text as description
            return AnalysisResult(
                entry_index=-1,  # caller must fill in
                timestamp="",  # caller must fill in
                input_type=input_type,
                description=raw[:500],
                category="other",
                key_elements=[],
                analyzed_at=now_iso(),
                status="completed",
            )
        return AnalysisResult(
            entry_index=-1,
            timestamp="",
            input_type=input_type,
            description=parsed.get("description", raw[:500]),
            category=parsed.get("category", "other"),
            key_elements=parsed.get("key_elements", []),
            analyzed_at=now_iso(),
            status="completed",
        )

    @staticmethod
    def _extract_text(response) -> str:
        """Extract plain text from an Anthropic message response."""
        parts: list[str] = []
        for block in response.content:
            if hasattr(block, "text"):
                parts.append(block.text)
        return "\n".join(parts).strip()

    @staticmethod
    def _parse_json_safe(text: str) -> Optional[dict]:
        """Try to parse JSON from *text*, tolerating markdown fences."""
        # Strip markdown code fences if present
        cleaned = text.strip()
        if cleaned.startswith("```"):
            # Remove first and last lines (fences)
            lines = cleaned.split("\n")
            if len(lines) >= 3:
                cleaned = "\n".join(lines[1:-1])
        try:
            return json.loads(cleaned)
        except json.JSONDecodeError:
            return None


# ---------------------------------------------------------------------------
# AnalysisQueue — async serial queue for realtime mode
# ---------------------------------------------------------------------------

_SENTINEL = object()


class AnalysisQueue:
    """Background serial queue that processes analysis tasks one at a time.

    This guarantees that writes to each pipeline's ``ai_analyses.json``
    are strictly serial, eliminating concurrent-write risks.
    """

    def __init__(self, config: "Config", workspace_dir: Path) -> None:
        self._config = config
        self._workspace_dir = workspace_dir
        self._queue: queue.Queue = queue.Queue()
        self._analyzer = ImageAnalyzer(config)
        self._thread = threading.Thread(
            target=self._worker, daemon=True, name="ai-analysis-queue"
        )
        self._thread.start()

    def enqueue(
        self,
        pipeline_name: str,
        entry_index: int,
        entry: dict,
    ) -> None:
        """Add an analysis task to the queue."""
        self._queue.put((pipeline_name, entry_index, entry))

    def drain(self, timeout: float = 120.0) -> None:
        """Block until the queue is empty or *timeout* seconds elapse."""
        deadline = time.monotonic() + timeout
        while not self._queue.empty() and time.monotonic() < deadline:
            time.sleep(0.2)
        # Also wait for the worker thread to finish its current task
        self._queue.join()

    def shutdown(self) -> None:
        """Signal the worker thread to exit and wait."""
        self._queue.put(_SENTINEL)
        self._thread.join(timeout=5)

    # -- internal ---------------------------------------------------------

    def _worker(self) -> None:
        """Consume tasks from the queue one at a time."""
        while True:
            item = self._queue.get()
            if item is _SENTINEL:
                self._queue.task_done()
                break
            pipeline_name, entry_index, entry = item
            try:
                self._process_entry(pipeline_name, entry_index, entry)
            except Exception:
                logger.exception("AI analysis queue: task failed")
            finally:
                self._queue.task_done()

    def _process_entry(
        self,
        pipeline_name: str,
        entry_index: int,
        entry: dict,
    ) -> None:
        input_type = entry.get("input_type", "")
        content = entry.get("input_content", "")
        user_hint = entry.get("description", "")
        timestamp = entry.get("timestamp", "")

        # Determine the store path
        store_path = (
            self._workspace_dir
            / "pipelines"
            / pipeline_name
            / "ai_analyses.json"
        )
        store = AnalysisStore(store_path, pipeline_name=pipeline_name)

        # Skip if already analysed
        if store.has_analysis(entry_index, timestamp):
            return

        result: Optional[AnalysisResult] = None

        if input_type == "image" and Path(content).exists():
            result = self._analyzer.analyze_image(
                Path(content), user_hint=user_hint
            )
        elif input_type == "url":
            result = self._analyzer.analyze_url(content, user_hint=user_hint)
        else:
            return  # not an analysable type

        if result is None:
            result = AnalysisResult.failed(
                entry_index=entry_index,
                timestamp=timestamp,
                input_type=input_type,
                error="AI analysis returned None (SDK unavailable or no API key)",
            )
        else:
            result.entry_index = entry_index
            result.timestamp = timestamp

        store.set_model(self._analyzer._model)
        store.append(result)


# ---------------------------------------------------------------------------
# Top-level convenience functions for workspace-level operations
# ---------------------------------------------------------------------------


def batch_analyze_workspace(
    config: "Config",
    workspace_dir: Path,
    workspace_meta,
) -> bool:
    """Daily-report mode: batch-analyse all un-analysed image/url entries.

    Iterates each pipeline, reads ``context.json`` + ``ai_analyses.json``,
    finds entries without analysis, and calls the AI for each batch.

    Returns ``True`` if any new analyses were produced.
    """
    from .pipeline import PipelineManager

    if not _ANTHROPIC_AVAILABLE:
        _warn_no_anthropic()
        return False

    analyzer = ImageAnalyzer(config)
    if not analyzer.available:
        return False

    pm = PipelineManager(workspace_dir)
    any_new = False

    for pipeline_name in pm.list_pipelines():
        entries = pm.get_entries(pipeline_name)
        store_path = (
            workspace_dir / "pipelines" / pipeline_name / "ai_analyses.json"
        )
        store = AnalysisStore(store_path, pipeline_name=pipeline_name)

        # Build pipeline-level context for daily_report
        meta = pm.get_pipeline_meta(pipeline_name)
        ctx_parts = [f"Pipeline: {pipeline_name}"]
        if meta.get("description"):
            ctx_parts.append(f"Description: {meta['description']}")
        if meta.get("goal"):
            ctx_parts.append(f"Goal: {meta['goal']}")
        pipeline_context = "\n".join(ctx_parts)

        # Collect un-analysed image/url entries
        to_analyze: list[tuple[int, dict]] = []
        for idx, entry in enumerate(entries):
            itype = entry.get("input_type", "")
            ts = entry.get("timestamp", "")
            if itype in ("image", "url") and not store.has_analysis(idx, ts):
                to_analyze.append((idx, entry))

        if not to_analyze:
            continue

        # Batch in groups of ai_batch_size
        batch_size = getattr(config, "ai_batch_size", 10)
        for batch_start in range(0, len(to_analyze), batch_size):
            batch = to_analyze[batch_start : batch_start + batch_size]
            batch_entries = [e for _, e in batch]

            results = analyzer.batch_analyze_entries(
                batch_entries,
                pipeline_name=pipeline_name,
                pipeline_context=pipeline_context,
            )

            for (idx, entry), result in zip(batch, results):
                ts = entry.get("timestamp", "")
                itype = entry.get("input_type", "")
                if result is None:
                    result = AnalysisResult.failed(
                        entry_index=idx,
                        timestamp=ts,
                        input_type=itype,
                        error="AI analysis returned None",
                    )
                else:
                    result.entry_index = idx
                    result.timestamp = ts
                store.append(result)
                any_new = True

        store.set_model(analyzer._model)

    return any_new


def generate_daily_summary(
    config: "Config",
    workspace_dir: Path,
    workspace_meta,
) -> Optional[str]:
    """Daily-report mode: generate a cross-pipeline work summary.

    Reads each pipeline's ``ai_analyses.json``, builds a text-only
    prompt with all descriptions, and asks the AI for a daily summary.
    Saves the result to ``<workspace>/ai_daily_summary.json``.

    Returns the overall summary text, or ``None`` on failure.
    """
    from .pipeline import PipelineManager

    if not _ANTHROPIC_AVAILABLE:
        _warn_no_anthropic()
        return None

    analyzer = ImageAnalyzer(config)
    if not analyzer.available:
        return None

    pm = PipelineManager(workspace_dir)
    pipeline_texts: list[str] = []

    for pipeline_name in pm.list_pipelines():
        store_path = (
            workspace_dir / "pipelines" / pipeline_name / "ai_analyses.json"
        )
        store = AnalysisStore(store_path, pipeline_name=pipeline_name)
        completed = store.get_all_completed()

        meta = pm.get_pipeline_meta(pipeline_name)

        lines = [f"### Pipeline: {pipeline_name}"]
        if meta.get("description"):
            lines.append(f"Description: {meta['description']}")
        if meta.get("goal"):
            lines.append(f"Goal: {meta['goal']}")
        lines.append(f"Entries analysed: {len(completed)}")
        for a in completed:
            lines.append(f"- [{a.get('category', '?')}] {a.get('description', '?')}")
        pipeline_texts.append("\n".join(lines))

    if not pipeline_texts:
        return None

    pipeline_data_text = "\n\n".join(pipeline_texts)
    summary_dict = analyzer.generate_daily_summary_text(pipeline_data_text)

    if summary_dict is None:
        return None

    # Save to workspace-level file
    summary_data = {
        "generated_at": now_iso(),
        "model": analyzer._model,
        "pipeline_summaries": summary_dict.get("pipeline_summaries", {}),
        "overall_summary": summary_dict.get("overall_summary", ""),
    }
    write_json(workspace_dir / "ai_daily_summary.json", summary_data)

    # Also write per-pipeline summaries back into their ai_analyses.json
    for pipeline_name, ps in summary_dict.get("pipeline_summaries", {}).items():
        store_path = (
            workspace_dir / "pipelines" / pipeline_name / "ai_analyses.json"
        )
        if store_path.exists():
            store = AnalysisStore(store_path, pipeline_name=pipeline_name)
            store.set_daily_summary(ps)

    return summary_dict.get("overall_summary", "")
